Repository cilium/proxy, pull requests merged in 2023-04, with the labels that each got.

#153 ci: introduce cilium integration test
  .github/workflows/cilium-integration-tests.yaml
Labels: enhancement

#173 patches: Update for upstreamed versions
  WORKSPACE
  cilium/BUILD
  cilium/websocket.cc
  cilium/websocket.h
  go/envoy/extensions/filters/network/tcp_proxy/v3/tcp_proxy.pb.go
  go/envoy/extensions/filters/network/tcp_proxy/v3/tcp_proxy.pb.validate.go
  patches/0001-network-Add-callback-for-upstream-authorization.patch
  patches/0002-upstream-Add-callback-for-upstream-authorization.patch
  patches/0003-connection-Make-isHalfCloseEnabled-const.patch
  patches/0004-tcp_proxy-Add-filter-state-proxy_read_before_connect.patch
  patches/0004-tcp_proxy-Add-option-to-read-before-connect.patch
  patches/0005-router-Do-not-crash-if-SNI-was-already-set-with-auto.patch
  patches/0005-router-Do-not-set-SNI-or-SAN-due-to-auto_sni-or-auto.patch
  patches/0006-tcmalloc-Update-for-arm64-support.patch
  tests/cilium_websocket_codec_integration_test.cc
  tests/cilium_websocket_decap_integration_test.cc
  tests/cilium_websocket_encap_integration_test.cc
Labels: clean-up

#183 patches: Update for upstreamed versions
  WORKSPACE
  cilium/BUILD
  cilium/websocket.cc
  cilium/websocket.h
  patches/0001-network-Add-callback-for-upstream-authorization.patch
  patches/0002-upstream-Add-callback-for-upstream-authorization.patch
  patches/0003-connection-Make-isHalfCloseEnabled-const.patch
  patches/0004-tcp_proxy-Add-filter-state-proxy_read_before_connect.patch
  patches/0004-tcp_proxy-Add-option-to-read-before-connect.patch
  patches/0005-router-Do-not-crash-if-SNI-was-already-set-with-auto.patch
  patches/0005-router-Do-not-set-SNI-or-SAN-due-to-auto_sni-or-auto.patch
  patches/0006-tcmalloc-Update-for-arm64-support.patch
  tests/cilium_websocket_codec_integration_test.cc
  tests/cilium_websocket_decap_integration_test.cc
  tests/cilium_websocket_encap_integration_test.cc
Labels: backport/1.23
