Repository cilium/proxy, pull requests merged in 2024-10, with the labels that each got.

#960 policy: Add warning log if worker threads take longer than 100ms to update policies
  cilium/network_policy.cc
Labels: backport/1.29

#974 policy: Use timing-safe string comparison
  cilium/network_policy.cc
Labels: needs-backport/1.29

#982 v1.29 Backports 2024-10-23
  cilium/network_policy.cc
Labels: kind/backports, backport/1.29

#984 build: Enable envoy.transport_sockets.upstream_proxy_protocol
  envoy_build_config/extensions_build_config.bzl
Labels: needs-backport/1.29

#985 v1.29 Backports 2024-10-24
  envoy_build_config/extensions_build_config.bzl
Labels: kind/backports, backport/1.29

#992 policy: Drop on missing SDS secret and no default value inline
  cilium/network_policy.cc
  tests/cilium_http_integration_test.cc
  tests/cilium_http_upstream_integration_test.cc
  tests/cilium_network_policy_test.cc
Labels: bug

#996 policy: Log info on new stream
  cilium/network_policy.cc
Labels: kind/enhancement
