Repository cilium/proxy, pull requests merged in 2024-04, with the labels that each got.

#674 bpf: fix error propagation for bpf syscalls
  cilium/bpf.cc
Labels: needs-backport/1.27

#658 build: remove duplicated make targets
  Makefile
  Makefile.dev
Labels: clean-up

#680 [1.27] bpf: fix error propagation for bpf syscalls
  cilium/bpf.cc
Labels: kind/backports, backport/1.27

#659 bpfmetadata: refactor getMetadata by extracting methods
  cilium/bpf_metadata.cc
  cilium/bpf_metadata.h
  cilium/network_policy.h
Labels: clean-up

#698 tests: Update certs
  WORKSPACE
  patches/0005-ci-tests-Re-issue-test-certs-33389.patch
  tests/cilium_tls_http_integration_test.cc
  tests/cilium_tls_tcp_integration_test.cc
Labels: needs-backport/1.27

#699 v1.27 Backports 2024-04-09
  WORKSPACE
  patches/0005-ci-tests-Re-issue-test-certs-33389.patch
  tests/cilium_tls_http_integration_test.cc
  tests/cilium_tls_tcp_integration_test.cc
Labels: kind/backports, backport/1.27

#707 build: Enable local_ratelimit and http_inspector listener filters
  envoy_build_config/extensions_build_config.bzl
Labels: kind/enhancement, needs-backport/1.27

#708 api: Remove explicit go get in favor of Renovate
  Makefile.api
Labels: kind/enhancement, needs-backport/1.27

#711 make: Install clang without checking /usr/lib/llvm-17
  Makefile
Labels: enhancement

#729 starter: fix Envoy program and argument order
  starter/main.cc
Labels: bug
