Repository cilium/proxy, pull requests merged in 2024-02, with the labels that each got.

#564 patches: Remove duplicated upstream callbacks
  patches/0002-upstream-Add-callback-for-upstream-authorization.patch
Labels: needs-backport/1.27

#570 v1.27 Backports 2024-02-21
  patches/0002-upstream-Add-callback-for-upstream-authorization.patch
Labels: kind/backports, backport/1.27

#580 tests: Reduce flakiness
  tests/cilium_http_integration_test.cc
Labels: clean-up
