Repository cilium/proxy, pull requests merged in 2024-08, with the labels that each got.

#888 v1.29 Backports 2024-08-14
  .github/workflows/build-envoy-images-release.yaml
Labels: kind/backports, backport/1.29

#891 tls_wrapper: Do not use raw socket if no policy is found
  cilium/tls_wrapper.cc
Labels: backport/1.29

#890 tls_wrapper: Do not use raw socket if no policy is found
  cilium/tls_wrapper.cc
Labels: kind/enhancement
