Repository cilium/proxy, pull requests merged in 2024-01, with the labels that each got.

#486 build: Enable proxy_protocol filter
  envoy_build_config/extensions_build_config.bzl
Labels: needs-backport/1.27

#487 v1.27 Backports 2024-01-16
  envoy_build_config/extensions_build_config.bzl
Labels: kind/backports, backport/1.27

#506 [v1.27] api: socket options shouldn't set SO_REUSEPORT on listener socket
  cilium/socket_option.h
Labels: bug, backport/1.27
