Repository cilium/proxy, pull requests merged in 2025-01, with the labels that each got.

#1127 Remove the SO_LINGER option
  cilium/bpf_metadata.cc
Labels: bug

#1128 Remove the SO_LINGER option
  cilium/bpf_metadata.cc
Labels: bug, needs-backport/1.30

#1151 bpf_metadata: set TCP keep alive socket options without Envoy SocketOption
  cilium/bpf_metadata.cc
Labels: needs-backport/1.31
