Repository cilium/proxy, pull requests merged in 2025-03, with the labels that each got.

#1172 policy: Use source pod's egress policy if available
  cilium/bpf_metadata.cc
  cilium/bpf_metadata.h
  cilium/filter_state_cilium_policy.cc
  cilium/filter_state_cilium_policy.h
  cilium/l7policy.cc
  cilium/network_filter.cc
  cilium/network_policy.h
  tests/bpf_metadata.cc
  tests/metadata_config_test.cc
Labels: bug

#1188 v1.31 Backports 2025-02-26
  .github/workflows/build-envoy-image-ci.yaml
  .github/workflows/build-envoy-images-release.yaml
Labels: kind/backports, backport/1.31

#1194 v1.31 Backports 2025-03-05
  cilium/bpf_metadata.cc
  cilium/bpf_metadata.h
  cilium/filter_state_cilium_policy.cc
  cilium/filter_state_cilium_policy.h
  cilium/l7policy.cc
  cilium/network_filter.cc
  cilium/network_policy.h
  tests/bpf_metadata.cc
  tests/metadata_config_test.cc
Labels: kind/backports, backport/1.31

#1202 deps: Bump ubuntu runtime image to 24.04
  .github/renovate.json5
  Dockerfile
Labels: needs-backport/1.31

#1206 v1.31 Backports 2025-03-12
  cilium/api/bpf_metadata.proto
  cilium/bpf_metadata.cc
  cilium/bpf_metadata.h
  cilium/network_policy.cc
  go/cilium/api/bpf_metadata.pb.go
  go/cilium/api/bpf_metadata.pb.validate.go
Labels: kind/backports, backport/1.31

#1217 build: Use libc++ configuration
  Makefile
Labels: needs-backport/1.31

#1218 v1.31 Backports 2025-03-19
  Makefile
Labels: kind/backports, backport/1.31

#1241 clang: Add clang macro check
  cilium/network_policy.cc
Labels: needs-backport/1.32
